image: uber/android-build-environment:latest
pipelines:
  default:
    - step:
        script:
          - yes | sdkmanager --licenses && yes | sdkmanager --update
          - echo y | android update sdk --filter "build-tools-28.0.3,android-28,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository" --no-ui -a
          - yes | sdkmanager --licenses && yes | sdkmanager --update
          - ./gradlew assembleDebug
          - ./gradlew connectedAndroidTest