image: uber/android-build-environment:latest
pipelines:
  default:
    - step:
        script:
          - echo y | android update sdk --filter "build-tools-24.0.3,android-25,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository" --no-ui -a
          - ./gradlew assembleDebug
          - echo yes | sdkmanager --licenses
          - ./gradlew connectedAndroidTest